include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    avoid_catches_without_on_clauses: false
    avoid_dynamic_calls: false
    use_null_aware_elements: true
