include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    no_default_cases: false
    sort_pub_dependencies: false
    avoid_catches_without_on_clauses: false
    avoid_dynamic_calls: false
    use_null_aware_elements: true

formatter:
  trailing_commas: preserve

analyzer:
  errors:
    strict_raw_type: ignore
    use_setters_to_change_properties: ignore
  exclude:
    - "**/icons.dart"
