include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    unnecessary_const: true

    no_default_cases: false
    sort_pub_dependencies: false
    avoid_dynamic_calls: false
    use_null_aware_elements: true

formatter:
  trailing_commas: preserve

analyzer:
  errors:
    strict_raw_type: ignore
    use_setters_to_change_properties: ignore
  exclude:
    - "**/icons.dart"
