arb-dir: lib/l10n
template-arb-file: basf_components_en.arb
output-dir: lib/l10n/localizations
output-localization-file: basf_components_localizations.dart
output-class: BasfComponentsLocalizations
nullable-getter: false
use-escaping: true
synthetic-package: false