name: basf_flutter_components
description: A collection of BASF Style components such as Buttons, Theming, etc...
version: 2.6.6

homepage: https://github.com/BASF-Mobile-Solutions/basf_flutter_components
repository: https://github.com/BASF-Mobile-Solutions/basf_flutter_components
issue_tracker: https://github.com/BASF-Mobile-Solutions/basf_flutter_components/issues

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.0.0

  path_provider: ^2.1.5
  rive: ^0.13.20
  transparent_image: ^2.0.1

  mobile_scanner: ^7.0.0
  # Setup related config in your app in your app
  permission_handler: ^11.4.0
  # Setup related config in your app
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  very_good_analysis: ^7.0.0

flutter_gen:
  output: lib/utils/gen/
  assets:
    outputs:
      package_parameter_enabled: true
  integrations:
    rive: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/rive/
    - assets/images/

  fonts:
    - family: BasfIcons
      fonts:
        - asset: lib/fonts/BasfIcons.ttf
    - family: Roboto
      fonts:
        - asset: lib/fonts/roboto/Roboto-Thin.ttf
          weight: 200
        - asset: lib/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: lib/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: lib/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: lib/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: lib/fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: lib/fonts/roboto/Roboto-ThinItalic.ttf
          style: italic
          weight: 200
        - asset: lib/fonts/roboto/Roboto-LightItalic.ttf
          style: italic
          weight: 300
        - asset: lib/fonts/roboto/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: lib/fonts/roboto/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: lib/fonts/roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: lib/fonts/roboto/Roboto-BlackItalic.ttf
          style: italic
          weight: 900
