name: basf_flutter_components
description: A collection of BASF Style components.
version: 0.0.1
homepage: https://github.com/cgutierr-zgz/basf_flutter_components

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  onetrust_publishers_native_cmp: ^6.29.0
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: