name: basf_flutter_components
description: A collection of BASF Style components, such as Buttons, Colors, Icons, etc...
version: 0.1.0
homepage: https://github.com/BASF-Mobile-Solutions/basf_flutter_components

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  assets:
    - assets/
  fonts:
    - family: BasfIcons
      fonts:
        - asset: lib/fonts/BasfIcons.ttf
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-Thin.ttf
          weight: 200
        - asset: fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: fonts/roboto/Roboto-ThinItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/roboto/Roboto-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/roboto/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/roboto/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/roboto/Roboto-BlackItalic.ttf
          style: italic
          weight: 900
