name: basf_flutter_components
description: A collection of BASF Style components, such as Buttons, Colors, Icons, etc...
version: 0.1.0
homepage: https://github.com/BASF-Mobile-Solutions/basf_flutter_components

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  fonts:
    - family: BasfIcons
      fonts:
        - asset: lib/fonts/BasfIcons.ttf